### ISSUE TITLE
kubefed-controller-manager fails to start up

### ISSUE THREAD

**Issue by alexbrand** [kubernetes-sigs/kubefed#928] opened 2019-05-24 14:28 UTC
**What happened**: The kubefed-controller-manager enters a crash loop with the following error in the logs:

```
Kubefed controller-manager version: version.Info{Version:"v0.1.0-rc1", GitCommit:"f63eb03e20bc905e9a4c8b27ae9d999e096e66f0", GitTreeState:"clean", BuildDate:"2019-05-22T20:47:54Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
W0524 14:23:13.512397       1 client_config.go:549] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
F0524 14:23:13.812711       1 controller-manager.go:203] Error retrieving KubefedConfig "kube-federation-system/kubefed": no matches for kind "KubefedConfig" in version "core.kubefed.k8s.io/v1beta1".
```

**What you expected to happen**: The kubefed-controller-manager to start up properly.

**How to reproduce it (as minimally and precisely as possible)**:

Install kubefed using the `v0.1.0-rc1` helm chart:
```
helm install kubefed-charts/kubefed --name kubefed \ 
  --version=0.1.0-rc1 --namespace kube-federation-system
```

**Anything else we need to know?**:

I believe the problem is that the container image does not have all the commits in `v0.1.0-rc1`. The git commit hash in the error message is:
```
f63eb03e20bc905e9a4c8b27ae9d999e096e66f0
```

However, the last git commit hash in the `v0.1.0-rc1` release is:
```
5fab26a45f59c248d6064899fc03fc32bea9ccdd
```

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-26T00:04:52Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-03-20T16:54:39Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Federation version: `v0.1.0-rc1`
- Install method (helm vs script) `helm`
- Install configuration (namespaced vs cluster-scoped)
- Others

/kind bug

**Comment by marun** [comment] 2019-05-27 15:04
Thank you for reporting this!  It appears our image build pipeline broke after publishing that bad image.  I don't have the necessary information to fix it today, and I'll make sure this issue is updated as soon as a fixed image becomes available.

**Comment by marun** [comment] 2019-05-27 15:40
@alexbrand  I am unable to update the rc1 image at this time, but I've tested the [v0.1.0-rc2](https://github.com/kubernetes-sigs/kubefed/releases/tag/v0.1.0-rc2) image and it appears healthy.  Please close this issue if the rc2 fixes the problem you were seeing.

**Closed** 2019-05-28 07:40 UTC
Labels: kind/bug, priority/critical-urgent

**Comment by queeno** [comment] 2019-07-01 10:36
Hi @marun 
I've just attempted to install v0.1.0-rc3 on my GKE via helm and I am seeing the exact same issue that @alexbrand reported:

```
❯ helm install kubefed-charts/kubefed --name kubefed --version=0.1.0-rc3 --namespace kube-federation-system
```

```
❯ kubectl logs kubefed-controller-manager-6c956f7679-kxrdq
KubeFed controller-manager version: version.Info{Version:"v0.1.0-rc3", GitCommit:"d188d227fe3f78f33d74d9a40b3cb701c471cc7e", GitTreeState:"clean", BuildDate:"2019-06-25T00:46:45Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
W0701 10:27:51.777589       1 client_config.go:549] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0701 10:27:52.066108       1 controller-manager.go:206] Setting Options with KubeFedConfig "kube-federation-system/kubefed"
F0701 10:28:22.184440       1 controller-manager.go:320] Error updating KubeFedConfig "kube-federation-system/kubefed": Timeout: request did not complete within requested timeout 30s
```

Is version `0.1.0-rc3` also broken?

**Comment by marun** [comment] 2019-07-01 13:46
> Is version `0.1.0-rc3` also broken?

@queeno The rc1 image was broken for all users.  rc3 has been reportedly installed successfully by many users, but you are the second person to report that deployment on GKE fails to a problem with the validation webhook.  This suggests that a new issue be filed.

Here is a slack thread digging into the problem:

https://kubernetes.slack.com/archives/C09R1PJR3/p1561534537123100

It's not clear to me whether the problem is specific to GKE or Kube 1.13 (kubefed ci currently runs against 1.14). If you have specific expertise with GKE your help in resolving this issue would be greatly appreciated.

**Comment by queeno** [comment] 2019-07-01 20:11
Hi @marun 

Thanks very much for your reply.
I have thoroughly investigated this issue and opened a bug #1024.
If you have any thoughts, I would be mostly pleased if you could point me in the right direction.
Let's continue our discussion in that thread.
