### ISSUE TITLE
RSP Policy calculate is not right with `minReplicas`

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/kubefed#319] opened 2018-10-11 05:31 UTC
This is a follow up action for https://github.com/kubernetes-sigs/federation-v2/pull/288#discussion_r220407570

I created a RSP as this:

```
apiVersion: scheduling.federation.k8s.io/v1alpha1
kind: ReplicaSchedulingPreference
metadata:
  name: test-deployment
  namespace: test-namespace
spec:
  targetKind: FederatedDeployment
  totalReplicas: 10
  rebalance: true
  clusters:
   cluster1:
   - minReplicas: 2
     maxReplicas: 6
     weight: 2
   cluster2:
   - minReplicas: 4
     maxReplicas: 8
     weight: 3
```

And the result is cluster1 has 3 and cluster2 has 7, and my expectation is cluster1 should have 4 while cluster2 should have 6.

/cc @irfanurrehman @quinton-hoole

**Comment by tghartland** [comment] 2018-10-30 16:49
I have added some logging to the Plan function to try to see what is going on here. I have it pushed to a branch [here](https://github.com/tghartland/federation-v2/blob/debug-319/pkg/controller/util/planner/planner.go#L104).

In this example, the issue is that is first allocates the minimum number of replicas to each cluster, and **then** uses the weighting to distribute the remaining replicas.
This is what the logging outputs for your example.
```
planner.go:104] About to place 10 replicas
planner.go:109] Want to assign minimum 4 to cluster2
planner.go:115] Removed 4 replicas from pool, 6 left
planner.go:109] Want to assign minimum 2 to cluster1
planner.go:115] Removed 2 replicas from pool, 4 left
planner.go:119] Placed minimum replicas in each cluster. 4 left to assign
planner.go:173] Starting distribution trial 0
planner.go:180] Weight sum is 5
planner.go:185] Distributing 4 remaining replicas in this trial loop
planner.go:190] Trying to distribute to cluster2, was already planning to give 4 replicas
planner.go:193] Want to distribute 3 more replicas to cluster2
planner.go:195] Because of remainingReplicas (4), can distribute 3 to cluster2
planner.go:227] Allocated 3 more replicas to cluster2
planner.go:190] Trying to distribute to cluster1, was already planning to give 2 replicas
planner.go:193] Want to distribute 2 more replicas to cluster1
planner.go:195] Because of remainingReplicas (1), can distribute 1 to cluster1
planner.go:227] Allocated 1 more replicas to cluster1
planner.go:243] Finished placing replicas
```
The important line is this one https://github.com/tghartland/federation-v2/blob/debug-319/pkg/controller/util/planner/planner.go#L192.
First it comes to cluster2 with weight 3, and extra is `(4*3 + 5 - 1) / 5 = 3.2`. The comment says it rounds up but it actually rounds down to 3. It gives 3 replicas to cluster2 and removes 3 from remainingReplicas. Then when it gets to cluster1 on the next loop, there is only one more replica to distribute.

I'm looking at that equation and I can't even figure out what it's doing.  
Rearranged it is `(remaining*(weight/sum)) + 1 - (1/sum)`
It sort of makes sense, `r*w/s` is the fraction of the remaining replicas that the cluster wants, and the `+1` could be to ensure that it always allocates at least 1 so that it doesn't get stuck. But the `1/sum`?

Would it not be better to convert to floats as an intermediate and then `math.Ceil(remaining*(weight/sum))`? This would ensure that as long as there are clusters with weight > 0, it will keep allocating at least 1 replica per loop, starting with the highest weight cluster.

That still isn't a fix to the problem in this issue though, because it would still give 3 replicas to cluster2 and then 1 to cluster1. The actual replicas that each cluster wants is
```
>>> 4*(3/5) # cluster 2
2.4
>>> 4*(2/5) # cluster 1
1.6
```
What you want is both of these to be rounded to 2. That gives you the overall best solution. The problem then is that if you have 20 clusters with weight 1 they're going to round to 0 every time. At least 1 replica should be allocated, so
```
extra := maxInt64(1, int64(math.Round(remaining*weight/sum)))
```
Maybe this doesn't work as well in other scenarios, I don't know, but it seems like the best option for this input.

**Comment by tghartland** [comment] 2018-10-31 11:06
If you have less totalReplicas than the sum of minReplicas on each cluster, the current method assigns all replicas to the cluster with the highest weight. It tries to satisfy the minReplicas requirement but in doing so ignores the weight balancing. Is this preferable to satisfying the weight first and ignoring the minReplicas limit on each?

For instance if you have
```
totalReplicas: 6
rebalance: true
clusters:
  cluster1:
    minReplicas: 6
    weight: 1
  cluster2:
    minReplicas: 6
    weight: 2
```
you get
* cluster1: 0 replicas
* cluster2: 6 replicas

Is that better than
* cluster1: 2 replicas
* cluster2: 4 replicas
?

**Comment by gyliu513** [comment] 2018-11-01 03:18
Thanks @tghartland my thinking is that 

- if the number of `totalReplicas` greater than sum of `minReplicas`, we can allocate the replicas as allocate `minReplicas` first, then allocate the remaining based on weight.
-  if the number of `totalReplicas` less than sum of `minReplicas`, we can allocate the replicas directly based on weight.

@irfanurrehman @tghartland WDYT?

**Comment by irfanurrehman** [comment] 2018-11-01 10:56
> The important line is this one https://github.com/tghartland/federation-v2/blob/debug-319/pkg/controller/util/planner/planner.go#L192.
> First it comes to cluster2 with weight 3, and extra is `(4*3 + 5 - 1) / 5 = 3.2`. The comment says it rounds up but it actually rounds down to 3. It gives 3 replicas to cluster2 and removes 3 from remainingReplicas. Then when it gets to cluster1 on the next loop, there is only one more replica to distribute.
> 
> I'm looking at that equation and I can't even figure out what it's doing.
> Rearranged it is `(remaining*(weight/sum)) + 1 - (1/sum)`
> It sort of makes sense, `r*w/s` is the fraction of the remaining replicas that the cluster wants, and the `+1` could be to ensure that it always allocates at least 1 so that it doesn't get stuck. But the `1/sum`?

@tghartland the equation correctly distributes replicas in the ratio, giving the ceiling of the fractional value (rounding up) considering weights in descending order. This ensures that clusters with higher weights always get a minimum whole number of replicas considering the weighted ratio. So a cluster with higher weight can get an additional replica, but not the cluster with lower weight.

taking the values you considered
> `(4*3 + 5 - 1) / 5 = 3.2`. The comment says it rounds up but it actually rounds down to 3. It gives 3 replicas to cluster2 and removes 3 from remainingReplicas.

The actual number of replicas (out of 4) for first cluster in weight ration would be `4*3/5` = 2.4, which is rounded to 3 using the above equation.


the issue in the algorithm is because:
minReplicas limits are distributed in the first pass, then preallocated replicas (ones which are already distributed to clusters in the last reconcile) are added to this distribution (per cluster) and then ***only remaining replicas*** are distributed in weighted order using weight ratios (whereas all replicas should have been distributed using weighted ratio).
There are many other cases handled in between, the most prominent one being the rebalance case (in case some clusters are unable to schedule all replicas), which works if you preserve this order. And this is when we are considering that minReplica and maxReplica should be honoured always in weighted order.

One way of resolving this case I thought was to apply a correction value to the distribution (if min was already considered without weights in the first pass). The important point is to be able to arrive at the correction value. For example see a sample code I updated [here](a69d21aa463e8ccb83de2b5522537cca9b963851) (correction value is not appropriate in it though, its just to give the idea of what I am thinking).

Other would be to overhaul the complete algorithm as below:
A ideal distribution order (for the case where we observe the distribution issue) would be:
 - Arrange the clusters in weighted order.
 - Distribute replicas into clusters as per the weight ratios one cluster at a time
 - While assigning in the loop, check the upper and lower bounds (if specified)  per cluster, Limit the assigned replicas by the min or max bounds.
 - While distributing still consider already assigned replicas into clusters (in earlier passes) or because a target replicaset did preexist in the given cluster (adopted when federated) and also consider if some clusters are not able to schedule some or all replicas.

I do not have cycles to dive deep into this right now, feel free to try out if you have cycles but its fine as far as I am concerned if there is delay in fixing this.
Ensure you have read the intent of the algorithm as explained [here](https://github.com/kubernetes-sigs/federation-v2/blob/master/docs/userguide.md#replicaschedulingpreference)

**Closed** 2019-09-07 07:02 UTC
Labels: help wanted, kind/bug, lifecycle/rotten, priority/backlog
